First control point
Hackerman-ru/Elliptic-Curve-Tutorial pull request #1
Opened 2024-01-19 06:34 UTC by Hackerman-ru

2024-02-15 12:17 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Я обратил внимание на некоторые проблемы с rvo и nrvo у тебя в коде, из-за чего у тебя делаются лишние копирования.

Еще мне не нравится огромное количество кастов (часть из них эквивалентных reinterpret_cast). Я вообще опасаюсь подобных вещей особенно с массивами. И потому я бы хотел чтобы ты внимательно отнесся к этим местам и проверил их на ub по стандарту.

В остальном все замечания внес локально.

2024-02-15 12:17 UTC, DimaTrushin commented on main.cpp
Где система сборки? Как вообще твой проект собирать? Если это проект Visual Studio, то где файл проекта? Если это собирается cmake-ом, то где соответствующие файлы?

2024-02-15 12:17 UTC, DimaTrushin commented on main.cpp
> +//#include "../Elliptic-Curve-Tutorial/Uint/uint.h"
Зачем тебе git с его поддержкой версий, если ты оставляешь закомментированный код? Убрать. Гит помнит всю историю и хранит весь код. Если нужно поиграться, то создаешь локально тестовую ветку, там играешь, а потом через checkout пикаешь нужные файлы.

2024-02-15 12:17 UTC, DimaTrushin commented on main.cpp
> +int main() {
У тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "Primes.h"
#include "Except.h"

int main() {
  try {
    primes::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```

2024-02-15 12:17 UTC, DimaTrushin commented on util.h
> +    template<typename From, typename To>
А чем тебе стандартные шаблоны не подходят?
https://en.cppreference.com/w/cpp/types/is_convertible
или вот прям концепты
https://en.cppreference.com/w/cpp/concepts/convertible_to

2024-02-15 12:17 UTC, DimaTrushin commented on util.h
> +    concept is_convertible_reverse = is_convertible<From, To>;
Зачем?

2024-02-15 12:17 UTC, DimaTrushin commented on util.h
> +        { t[i] } -> is_convertible<W>;
Плохое название концепта is_convertible, вот тут в применении видно, что не ясно, что имеется в виду. Я бы переименовал твои концепты в is_convertible_to и is_convertible_from. Тогда понятно при использовании.

2024-02-15 12:17 UTC, DimaTrushin commented on util.h
> +        BINARY = 0b1,
Не используй стиль BINARY все капсом для чего-либо кроме макросов. Это будет сбивать пользователя, когда он будет видеть код с такими именами. Все привыкли, что так пишутся только макросы.

2024-02-15 12:17 UTC, DimaTrushin commented on util.h
> +
Следующие два enum class-а не выглядят как часть util.h. Это что-то более специфичное и возможно им есть место куда более подходящее, чем глобальное пространство.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +#endif
Какого хуя? Нахуя, а главное зачем? Почему не ввести constepxr переменную нужного типа или enum class или enum внутри struct, если нужны флаги? Почему используется макрос? Никогда не используй макросы для чего либо кроме как настройки компиляции единиц трансляции. Это очень низкоуровневый механизм и не надо его использовать для написания кода.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        using shift = size_t;
Я не очень понимаю имена типов. Названия как будто это переменные. Вот bucket это что такое? Это число корзин? Или это номер корзины? Или это id корзины? Что это за тип? Из его названия совершенно не ясно, что в нем хранится. Аналогично со всеми остальными типами.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            if constexpr (sizeof(T) * CHAR_BIT <= c_BUCKET_SIZE) {
- if constexpr позволяет писать уродливый код, чем ты и занимаешься тут. У тебя количество вложенных scope внутри конструктора -- 3, это максимально допустимое значение для кода в Linux. Более того, ты в конструкторе никак не пользуешься списком инициализации. Я бы переделал так
```cpp
template<is_convertible_to<bucket> T>
constexpr uint_t(T value) : m_buckets(split_into_buckets<T>(value)) {}

template<class T>
static std::array<bucket, c_BUCKET_NUMBER> split_into_buckets(T value);
```
Я еще бы ввел using для std::array, чтобы не писать такие длинные имена. И уже split_into_buckets специализируешь в зависимости от условий на T. И внутри него инициализируешь массив и потом возвращаешь его по rvo из функции.

- Еще возникает вопрос. Ты принимаешь value по значению, а не по ссылке. И тут не понятно какой из двух сценариев ты ожидаешь:
а) это легкий встроенный тип вроде int, short и так далее и потому так лучше принимать.
б) это тип у которого можно своровать внутренности
Для этого стоит еще концепт добавить для проверки того, что ты хочешь. Я думаю, что ты скорее всего (а) ожидаешь.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        }
У тебя же в util.h есть для этого концепт. Почему не используешь?

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        uint_t(const T& other) {
А что если у тебя коллизия произойдет между этим конструктором и предыдущим?

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        uint_t(const char* str) {
- А почему этот конструктор не constexpr?
- Ты уверен, что ты хочешь неявную конвертацию типов тут?
- В каком формате должна быть строка? Как это контролируется?
- Я не вижу обработки ошибок. Что если данные не корректны в строке?
- Мне не нравится, что конструктор занимается парсингом, но тут хотя бы это не сильно много кода, так что не страшно. Но я не могу понять, что делает цикл while в конструкторе. Особенно из-за того, что я понятия не имею в каком формате у тебя данные.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            *this = uint_t(str, find_type(str));
Не правильный способ звать конструктор в конструкторе. Это надо делать так
```cpp
uint_t(const std::string& str) : uint_t(str, find_type(str)) {}
```
Иначе у тебя тут вызывается два конструктора и одно мув присваивание (которое ничем не отличается от копирования, потому что объект с тяжелой локальной частью). Это дорого.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        uint_t(const std::string& str, StringType str_type) {
Мне не нравится, что у тебя конструктор занимается парсингом строк. Я бы выделил эту задачу в отдельный класс, который тут просто дергается. И тогда этот же класс будет парсить си строки. И весь код по парсингу будет в одном месте и он будет когерентный, не надо будет повторять и модифицировать код.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        static StringType find_type(const std::string& str) {
Плохо, что этот метод есть в uint_t. Он не относится к методам этого типа. Это парсинг строки. Надо весь парсинг вынести в отдельный класс, чтобы не засорять его методами uint_t. Кроме того, надо добавить обработку ошибок (некорретных данных в строке).

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        uint_t(const std::string& str, std::function<bucket(char)> map, shift shift_size) {
Это что за хрень!? Тут несколько вопросов возникает:
1) Что тут делают все эти параметры вроде map и shift_size? Как именно конструируется uint_t в этом случае? Конструктор ничего в своем имени про это не говорит. Нужны нормальные названия переменных как минимум. А еще лучше выделить это в статические методы и делать Named Cunstructor Idiom.
2) Нахрена пользователю этот конструктор? Как ты предполагаешь им пользоваться? Для чего? Если для каких-то вспомогательных построений, то сделай его приватным и зови только в статических методах и друзьях.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        auto operator<=>(const uint_t& other) const = default;
- Почему этот оператор inclass method, а следующий нет?
- У тебя много неявных конверсий, потому нет смысла делать этот оператор inclass, так как тогда ты запрещаешь конвертацию по первому аргументу, лучше сделать его default и friend.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        friend bool operator==(const uint_t& lhs, const uint_t& rhs) {
- сделай default.
- Если есть оператор ==, то надо явно объявить оператор !=.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            return result += rhs;
Так плохо писать. У тебя не затригерится nrvo и вместо этого будет move. Но так как у тебя нет разницы между move и copy, то это дорого. Потому надо делать так
```cpp
uint_t result = lhs;
result += rhs;
return result;
```
Дело в том, что nrvo тригерится только тогда, когда тип возвращаемого значения совпадает с типом выражения в return. Но если ты пишешь return result += rhs;, то оператор += возвращает ссылку uint_t&, а не uint_t, что мешает затригериться nrvo.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            return rhs += lhs;
Как вариант можно написать return std::move(rhs) + lhs;
Не знаю, будет ли какая-то разница по прозиводительности.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            return -(rhs -= lhs);   // or result version, if operator-() will be expensive
Да, тут нужна вспомогательная функция, которая делает все это Inplace.
сделай класс
```cpp
class CEcho {
public:
  CEcho() {
    std::cout << "ctor\n";
  }
  CEcho(const CEcho& other) {
    std::cout << "copy\n";
  }
  CEcho(CEcho&& other) noexcept {
    std::cout << "move\n";
  }
  CEcho& operator=(const CEcho& other) {
    std::cout << "copy asgn\n";
    return *this;
  }
  CEcho& operator=(CEcho&& other) noexcept {
    std::cout << "move asgn\n";
    return *this;
  }
  ~CEcho() {
    std::cout << "dtor\n";
  }
};
```
Унаследуйся от него и проверяй, что у тебя не вызываются лишние копирования или мувы.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            uint_t<bits> result;
Внутри шаблонного класса uint_t имя шаблона можно использовать без параметров. Убери. Это сбивает.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            divide(lhs, rhs, &remainder);
А почему ты не возваращаешь по значению с использованием nrvo и не пишешь так:
```cpp
uint_t remainder = divide(lhs, rhs);
```
????

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        uint_t operator-() const {
- Тебе нужна inplace версия этого оператора. Сделай приватную функцию для этих целей.
- Я только сейчас понял, что у тебя беззнаковый тип. А мы точно хотим такую операцию иметь? Наверное да. Но меня что-то смущает.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +                result[i] = ~(m_buckets[i]);
А это вообще правда так работает?

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            return (*this = *this * other);
Зачем тут скобки? Убрать.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            auto data = static_cast<uint64_t*>(static_cast<void*>(m_buckets.data()));
Это называется reinterpret_cast. Какого хуя? Почему тут такие касты? Ты уверен, что это не ub? Тут надо std::launder? Выглядит так, что ты работаешь не с теми типами, которые тебе нужны. У тебя нет проблем с little ending/big ending? Вообщем, я бы почитал внимательно стандарт и проверил, что в этом месте все ОК.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        }
Какого хуя постинкремент и преинкремент работают одинаково? Это нарушает ожидание от интерфейса. Постинкремент должен возвращать старое значение.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        }
А здесь почему только одна версия?

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        const bucket& operator[](size_t pos) const {
Нахуя этот оператор? Это противоречит семантике класса, ты просто пытаешься раскрыть имплементацию длинки. А у числа нет смылса в операторе скобки. Если хочешь преобразовывать свой тип к контейнеру, то лучше возвращать прокси объект, который будет имитировать контейнер, по которому можно пройтись и у которого будут операторы доступа и работать это будет так
```cpp
uint_t x;
auto x_buckets = x.buckets();
x_buckets[0];
for(auto bucket : x_buckets)
  ....
```
Где метод buckets возвращает прокси объект. А еще лучше сделать метод impl и только через него возвращать bucket, то есть
```cpp
uint_t x;
auto x_buckets = x.impl().buckets();
```

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        T convert_to() const {
Плохое название. Твой вызов будет выглядеть так
```cpp
uint_t<uint64_t> x;
uint64_t y = x.convert_to();
```
Сразу возникает вопрос, что за convert_to? Почему именно она и почему именно к этому типу? Если хочешь кастануть к подлежащему типу, то либо используй operator T() const, либо если не хочешь напрягать компилятор лишними неявными кастами, то сделай нормальное название метода. Например to_underlying_type или что-то в этом духе.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        std::string into_string(StringType str_type = StringType::DECIMAL) const {
Убрать в парсер.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        size_t clz() const {
Почему такое название? Как это вообще понять. Я когда увидел использование этого метода, был очень удивлен тем, что он должен делать.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +            static constexpr double_bucket c_HALF_BUCKET = static_cast<double_bucket>(1)
Почему не сделать функцию, которая будет считать это выражение? Дело в том, что это константа во время исполнения программы. Почему она считается тут в середине run-time кода?

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +                    + static_cast<double_bucket>(dividend[i + divisor_size - 2]);
Меня смущает, что тебе в бизнескоде нужно везде все кастовать.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +                        static_cast<bucket>(quotient_t) * static_cast<double_bucket>(divisor[j]);
название bucket не более информативно, чем uint_32_t.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +                        (static_cast<int64_t>(dividend[i + j - 1]) + carry) - (product & 0xffffffffLL);
- А тут какого хуя каст к знаковому?
- Что за магическая константа в конце? Сделай нормальное имя для маски.

2024-02-15 12:17 UTC, DimaTrushin commented on Uint/uint.h
> +        static constexpr size_t c_BUCKET_NUMBER = bits / c_BUCKET_SIZE;
убери в low case

2024-02-15 12:17 UTC, DimaTrushin commented on Field/Field.h
> +#endif
Чтобы не засорять клиентский код (в данном случае код Field.h) делается не так. Ты делаешь uint.h и в нем пишешь этот код, а тут уже просто подключаешь uint.h и просто пользуешься типом uint.

2024-02-15 12:17 UTC, DimaTrushin commented on Field/Field.h
> +        FieldElement(uint value, std::shared_ptr<const uint> p);
У тебя uint в твоей имплементации имеет тяжелую локальную часть и для него нет разницы между move и copy. Потому нет смысла его принимать by value, Лучше уж принимать const reference. Так хотя бы при вызове конструктора откуда-то из другого конструктора у тебя не будет лишнего копирования, а только передача адреса.

2024-02-15 12:17 UTC, DimaTrushin commented on Field/Field.h
> +        bool is_inversible() const;
is_invertible

2024-02-15 12:17 UTC, DimaTrushin commented on Field/Field.h
> +        FieldElement fast_pow(const uint& pow) const;
просто pow

2024-02-15 12:17 UTC, DimaTrushin commented on Field/Field.h
> +        FieldElement inverse() const;
Плохой интерфейс. Представь у тебя будет код
```cpp
FieldElement x;
x.inverse();
// и вот в этом месте ты буешь ахуевать, почему у тебя x не обратился
```
Я предпочитаю методы класса делать inplace методами, а если нужено создать новый объект, то я делаю static метод вида
```cpp
static FieldElement inverse(const uint& vlaue);

FieldElement x;
FieldElement y = FieldElement::inverse(x);
x.inverse();
assert(x == y);
```

2024-02-15 12:17 UTC, DimaTrushin commented on Field/Field.h
> +        const uint& get_p() const;
лучше сделай название метода modulus

2024-02-15 12:17 UTC, DimaTrushin commented on Field/Field.h
> +        std::string into_string(std::function<char(uint32_t)> map, size_t shift) const;
Не нравится мне наличие этих методов тут.

2024-02-15 12:17 UTC, DimaTrushin commented on Field/field.cpp
> +    }
- Мне не нравится такой подход тем, что ты сначала создаешь объект в некорректном состоянии, а потом уже поправляешь его состояние. Я предпочитаю делать метод normalize или что-то такое и писать так
```cpp
FieldElement::FieldElement(uint value, std::shared_ptr<const uint> p)
  : m_value(normalize(value, p)), m_p(p) {}
```
- Кроме того, как я понимаю, тут можно не проверять условие, а сразу сделать деление. Будет ли это лучше?
- Также normalize имеет возможность сделать assert если захочет и проверить данные до входа в тело конструктора.

2024-02-15 12:17 UTC, DimaTrushin commented on Field/field.cpp
> +    return -(rhs -= lhs);
Хотелось бы это место оптимизировать. Раз уж мы все обтачиваем.

2024-02-15 12:17 UTC, DimaTrushin commented on Field/field.cpp
> +    return lhs.m_value != rhs.m_value;
Если у тебя определен оператор ==, то ен надо писать явную имплементацию для !=. Вместо этого напиши
```cpp
return !(lhs == rhs);
```
Аналогично для всех других имплементаций.

2024-02-15 12:17 UTC, DimaTrushin commented on Field/field.cpp
> +    return lhs.m_value == rhs.m_value;
А ты уверен, что ты не хочешь учитывать modulus p при сравнении? Если у тебя элемент 5 из Z_7 и Z_11 у тебя будет ответ true. Мне не нравится такой подход. Это просто бессмысленно. Почему имплементация именно такая? Ну и банально транзитивность ломается в Z_7 у тебя (5 + 5) == 3, а в Z_11 это не так.

2024-02-15 12:17 UTC, DimaTrushin commented on Field/field.cpp
> +    assert(other.m_value < *m_p && "Field element value must be less than p");
Это не лучшие ассерты. Потому что этот метод вызывается на объкте класса и принимает объект класса. И ты проверяешь корректность этих объектов. Это не задача этого оператора. Это гарантируется инвариантами класса. То есть эти assert-ы должны быть в теле конструкторов и в конце мутирующих функций.
Тут в этом классе имеет смысл проверять что значения удовлетворяют каким-то условиям вроде не ноль или что-то такое, но то что ты написал этому тут не место.

2024-02-15 12:17 UTC, DimaTrushin commented on Field/field.cpp
> +    if (m_value > *m_p) {
А что если m_p != other.m_p??? Как это обрабатывается? Почему это вообще игнорируется?

2024-02-15 12:17 UTC, DimaTrushin commented on Field/field.cpp
> +    if (pow.convert_to<uint32_t>() & 1) {
Ааа, вот как это используется. А что если оно не конвертируется?

2024-02-15 12:17 UTC, DimaTrushin commented on Field/field.cpp
> +#ifdef ECG_BOOST
Этому явно тут не место. Как я писал, выдели uint.h и в нем объяви вспомогаетльные функции, которые ты хочешь использовать и сделай два cpp файла с разными имплементациями. И тут просто зови нужный метод.

2024-02-15 12:17 UTC, DimaTrushin commented on Field/field.cpp
> +    return FieldElement(std::move(value), m_p);
У тебя нет разницы между copy и move для твоего типа. Потому лучше принимать uint по константной ссылке.

2024-02-15 12:17 UTC, DimaTrushin commented on Encryption/el-gamal.h
> +        ElGamal() = delete;
Убрать. Если ты создаешь хоть один конструктор, то дефолтный удаляется.

2024-02-15 12:17 UTC, DimaTrushin commented on Encryption/el-gamal.h
> +            m_elliptic_curve(elliptic_curve), m_generator(generator), m_generator_order(generator_order) {};
Почему имплементация в h файле?

2024-02-15 12:17 UTC, DimaTrushin commented on Encryption/el-gamal.h
> +        const uint m_generator_order;
Какого хуя константные не статические поля в классе?

2024-02-15 12:17 UTC, DimaTrushin commented on Encryption/ecdsa.h
> +        ECDSA(const uint& field_order, const uint& security_level) {
Убрать имплементацию в cpp файл.

2024-02-15 12:17 UTC, DimaTrushin commented on Encryption/ecdsa.h
> +            } while (!((F(4) * a.fast_pow(3) + F(27) * b.fast_pow(2)).is_inversible()));
Выглядит как нарушение уровня абстракции. Ты тут явно пытаешься сгенерировать два элемента с каким-то условием. Тогда я бы ожидал, что-то вроде
```cpp
auto [a, b] = getEllipticCurveParameters();
```

2024-02-15 12:17 UTC, DimaTrushin commented on Encryption/ecdsa.h
> +        FieldElement generate_random_element(const Field& F) const;
Делай для методов класса заглушки в cpp файлах, чтобы не было проблем с линковкой, если ты эти хедеры куда-нибудь подключишь.

2024-02-15 12:17 UTC, DimaTrushin commented on EllipticCurve/elliptic-curve.h
> +    class EllipticCurvePoint;
Ну вот я бы ожидал вот в этом месте определение этого концепта. Потому что он сам по себе не имеет смысла, он актуален только для эллиптических кривых.

2024-02-15 12:17 UTC, DimaTrushin commented on EllipticCurve/elliptic-curve.h
> +        EllipticCurve(const FieldElement& a, const FieldElement& b, const Field& F);
Когда хранишь объекты какого-то типа и принимаешь в аргументах объекты этого же типа, которые собираешься положить внутрь, я бы ожидал кроме такого конструктора еще и принять их по rvalue ссылке, чтобы можно было украсть их содержимое.

2024-02-15 12:17 UTC, DimaTrushin commented on EllipticCurve/elliptic-curve.h
> +        EllipticCurvePoint<type> operator()(FieldElement x) const {
1) А почему тут аргумент по значению принимается?
2) Плохо, что ты сделал это оператором. Вот как понять по вызову, что происходит?
```cpp
EllipticCurve E;
E(3);// Вот что тут такое?
```
Потом, тут важно, что именно x подставляют, а не y? Если да, то что помешает пользователю сделать иначе? Имя метода никак про это не говорит. Думаю нужно заменить оператор на функцию с нормальным названием.

2024-02-15 12:17 UTC, DimaTrushin commented on EllipticCurve/elliptic-curve.h
> +        bool find_y(const FieldElement& x, FieldElement& y) const;
Не пиши методы после полей класса. Поля класса в самый конец. Как я их потом искать буду когда это все кодом обрастет?

2024-02-15 12:17 UTC, DimaTrushin commented on EllipticCurve/elliptic-curve.h
> +        const Field m_F;
Не делай константных полей. Это не имеет смысла. Ты можешь в инвариант класса добавить условие, что поля никогда не меняются. А так ты просто ломаешь семантику объекта.

2024-02-15 12:17 UTC, DimaTrushin commented on EllipticCurve/elliptic-curve.h
> +    uint random_uint();
Что эта хрень тут делает? Если эта штука глобальный рандомный генератор, то почему она не в отдельном хедере, а если это генератор для EllipticCurve, то какого хрена этот метод не спрятан в cpp файле для EllipticCurve, ну или хотя бы не сделан приватным и статическим методом?

2024-02-15 12:17 UTC, DimaTrushin commented on EllipticCurve/elliptic-curve.cpp
> +uint ECG::random_uint() {
не пиши так. Сделай
```cpp
namespace ECG {
uint random_uint() {...}
...
}
Оберни все в пространство имен и не пиши явный квалификатор пространства имен.
```

2024-02-15 14:23 UTC, Hackerman-ru commented on util.h
> +    template<typename From, typename To>
Они требуют implicit conversions, что мне мешает

2024-02-15 14:26 UTC, Hackerman-ru commented on util.h
> +    concept is_convertible_reverse = is_convertible<From, To>;
чтобы метод convert_to у uint можно было удобно зашаблонить, так как в концепт надо сначала написать второй шаблонный аргумент, но T туда написать нельзя, поэтому чтобы поменять их местами с bucket я его добавил

2024-04-02 10:25 UTC, Hackerman-ru commented on Uint/uint.h
> +        T convert_to() const {
я же конверчу к T, т.е. будет
```
uint_t<512> x = "999";
size_t y = x.convert_to<size_t>();
```

2024-04-03 12:54 UTC, Hackerman-ru commented on Uint/uint.h
> +            divide(lhs, rhs, &remainder);
он возвращает частное

2024-04-14 09:32 UTC, Hackerman-ru commented on Field/Field.h
> +#endif
Я бы не хотел скрывать uint_t, чтобы нормально его инклюдить и тестить в uint_test

2024-04-14 13:30 UTC, Hackerman-ru commented on Field/field.cpp
> +    return lhs.m_value == rhs.m_value;
Я во всех методах считаю, что пользователь проводит операции только над элементами из 1 поля. Если он захочет сравнить или сложить например элементы из разных полей, то будет UB

2024-04-14 13:54 UTC, Hackerman-ru commented on Field/field.cpp
> +    return -(rhs -= lhs);
А как его ускорить?

2024-04-14 17:58 UTC, Hackerman-ru commented on Uint/uint.h
> +        using shift = size_t;
Я просто не совсем понимаю, какое можно им имя дать

2024-04-20 18:17 UTC, Hackerman-ru commented on main.cpp
> +int main() {
Теперь отключил

2024-04-20 18:18 UTC, Hackerman-ru commented on Uint/uint.h
> +                result[i] = ~(m_buckets[i]);
да

2024-04-20 18:20 UTC, Hackerman-ru commented on Uint/uint.h
> +            auto data = static_cast<uint64_t*>(static_cast<void*>(m_buckets.data()));
Скорость в два раза выше, если из 32 битных шифтить 64 битные числа. Я, наверно, поменяю на uin64_t, как только сделаю рабочий FFT

2024-04-20 18:32 UTC, Hackerman-ru commented on Uint/uint.h
> +                    + static_cast<double_bucket>(dividend[i + divisor_size - 2]);
Ну тут детали имплементации алгоритма. Без кастов получается неэффективно

2024-04-20 18:34 UTC, Hackerman-ru commented on EllipticCurve/elliptic-curve.h
> +        EllipticCurve(const FieldElement& a, const FieldElement& b, const Field& F);
Сделал общий случай

2024-05-20 21:18 UTC, Hackerman-ru commented on Uint/uint.h
> +                        (static_cast<int64_t>(dividend[i + j - 1]) + carry) - (product & 0xffffffffLL);
- Это часть алгоса
- Ок

2024-05-22 11:14 UTC, merged